package de.mymiggi.r6.stats.wrapper;

public enum R6Rank
{
	UNRANKED, COPPER5, COPPER4, COPPER3, COPPER2, COPPER1, BRONZE5, BRONZE4, BRONZE3, BRONZE2, BRONZE1, SILVER5, SILVER4, SILVER3, SILVER2, SILVER1, GOLD3, GOLD2, GOLD1, PLATINUM3, PLATINUM2, PLATINUM1, DIAMOND, CHAMION;
}
